encord-team/encord-agents

docs/task_agents/runner.md
encord_agents/core/data_model.py
encord_agents/core/utils.py
encord_agents/fastapi/dependencies.py
encord_agents/gcp/wrappers.py
encord_agents/tasks/runner.py

Things to keep in mind:
1. Update doc string
2. Consistent naming
3. Make sure it works for all six cases [gcp, fastapi, task] x [with, without]

feat: add include args for label row listing

---

mkdocs.yml

Had to test that it works with Colab before I could do it

docs(fix): change branch name in config

---

docs/notebooks/prelabel_videos_with_bounding_boxes.ipynb

Generating a confidence > 1.0 can cause validation errors in the platform

misc: Small fixes (Typo and funky confidence)

---

encord_agents/core/ontology.py

misc: Docstring typo

---

docs/code_examples/modal/editor_add_bitmask.py
pyproject.toml
tests/fixtures.py

This could be based off of main and then big boy rebased.
Either doesn't matter.

misc: Remove unused ignores

---

encord_agents/tasks/runner.py

misc: More verbose TQDM Iterator

---

encord_agents/core/rich_columns.py
encord_agents/core/utils.py
encord_agents/tasks/runner.py

**Faster startup**
Instead of loading every task into a list, to it batched in `task-batch-size` to get faster startup.
**Progress bar:**
Make progress stick to the bottom of the terminal to avoid all the clutter.
https://github.com/user-attachments/assets/95fc6e90-ad00-47b4-96d5-46e77bcfccad
Also tested colab:
And vscode notebook looks "alright":

feat: faster startup and better progress

---

pyproject.toml

Shouldn't change anything hopefully?

chore: skif_if_set definitely wrong

---

docs/getting_started.md
docs/notebooks/mask_rcnn_on_videos.ipynb
docs/task_agents/index.md

https://encord-global.slack.com/archives/C039UCHMSBF/p1740505364157039

misc: Fix link

---

docs/editor_agents/examples/index.md
docs/editor_agents/gcp.md
docs/editor_agents/modal.md
docs/task_agents/runner_intro.md
encord_agents/core/dependencies/shares.py
encord_agents/fastapi/dependencies.py
encord_agents/gcp/dependencies.py
encord_agents/tasks/dependencies.py
encord_agents/tasks/runner.py

fix: Couple mkdocs warning

---

tests/fixtures.py
tests/integration_tests/tasks/test_queue_runner.py
tests/integration_tests/tasks/test_sequential_runner.py

Expanding on Frederik's tests for the Sequential runner, this does basic coverage for the Queue runner.
I think the tests are pretty comprehensive but will muse on further coverage

test: Tests for the Queue based runner

---

.gitignore
pyproject.toml
tests/fixtures.py
tests/integration_tests/tasks/test_queue_runner.py
tests/integration_tests/tasks/test_sequential_runner.py

Double checking that we're not loosing tasks.

test: test basics of sequential runner

---

encord_agents/tasks/runner.py

It's confusing in an LSP based environment that we have so many methods on the Runner objects. The end user should never need to use these methods. Hence make them private.
We can safely do this as pre 1.0.0

chore: Make methods private

---

docs/task_agents/runner_intro.md
encord_agents/tasks/runner.py
tests/integration_tests/tasks/test_sequential_runner.py
tests/test_tasks.py

Suppose that we want to enforce a required Ontology, dataset or whatever.
This will be used notably in making Docker examples.
Many tests added. Can discuss if all necessary

feat: Add optional callback

---

docker/clip-image-classification/Dockerfile
docker/clip-image-classification/README.md
docker/clip-image-classification/clip-image-classification.py
docker/clip-image-classification/requirements.txt
docker/detr-video-labeling/Dockerfile
docker/detr-video-labeling/README.md
docker/detr-video-labeling/detr-video-labeling.py
docker/detr-video-labeling/requirements.txt
docker/llm-document-classification/Dockerfile
docker/llm-document-classification/README.md
docker/llm-document-classification/llm-document-classification.py
docker/llm-document-classification/requirements.txt
docker/llm-image-captioning/Dockerfile
docker/llm-image-captioning/README.md
docker/llm-image-captioning/llm-image-captioning.py
docker/llm-image-captioning/requirements.txt
pyproject.toml

CLIP image classification,
LLM Image captioning,
Document classification.
Could do a central container. But this works fine

feat: Add Basic docker examples

---

encord_agents/core/constants.py
tests/test_misc.py

Not really sure about the test cases

fix: Fix editor url regex

---

docs/task_agents/sequential_runner.md

fix: Docs typo

---

docs/task_agents/queue_runner.md
docs/task_agents/sequential_runner.md

Following a refactor of how runners were in the code

fix: These references were now wrong

---

encord_agents/gcp/wrappers.py

As Past Jan31, migrate-to-enforcing-application/json-post-release.
This is currently un-tested automatically 🤔 
Needs comms

chore [DEPRECATION]: Do deprecation of old content type

---

.github/workflows/publish.yml
.github/workflows/pull-request.yml
.github/workflows/update-docs.yml

Current main wrong so should fail.
Additionally ensure that first created and last editted at are correct on the docs

CI: Check docs buildable on PR and fix last updated

---

encord_agents/tasks/runner/runner_base.py
tests/integration_tests/tasks/test_sequential_runner.py

Critical bug.
This worked
```python
@runner.stage("task-splitter")
def task_splitter(
label_row: LabelRowV2,
storage_item: StorageItem,
) -> str:
print(label_row.data_type, storage_item.item_type)
return IS_TEXT if storage_item.item_type in TEXT_TYPES else IS_NOT_TEXT
```
This didn't work
```python
@runner.stage("task-splitter")
def task_splitter(
storage_item: StorageItem,
) -> str:
return IS_TEXT if storage_item.item_type in TEXT_TYPES else IS_NOT_TEXT
```
The reason is that `list_label_rows_v2(data_hashes=[...])` does not return label rows in the same order as the data hashes. As a consequence, storage items got mixed up.

fix: storage item order

---

docs/dependencies.md
docs/notebooks/mask_rcnn_on_videos.ipynb
encord_agents/core/utils.py
encord_agents/core/video.py
encord_agents/tasks/dependencies.py
tests/integration_tests/tasks/test_task_dependencies.py

feat: [MLT-10] Add video Sampler

---

docs/code_examples/fastapi/fastapi_frame_classification.py
docs/code_examples/fastapi/fastapi_object_classification.py
docs/code_examples/fastapi/fastapi_recaption_video.py
docs/editor_agents/examples/index.md
docs/editor_agents/fastapi.md
docs/editor_agents/spec.md
encord_agents/fastapi/cors.py
encord_agents/fastapi/dependencies.py
tests/integration_tests/fastapi/test_dependencies.py

Following the introducion of get_encord_app, make it clear that this is the methodology moving forward.

style: Migrate everywhere to using new method

---

encord_agents/gcp/dependencies.py
tests/integration_tests/fastapi/test_dependencies.py

Mostly just to cover myself when adding PDF stuff

fix: [MLT-47] fix single frame for GCP. Add test coverage for FastAPI

---

mkdocs.yml
poetry.lock
pyproject.toml

Probably not necessary but was indeed straightforward

docs: [MLT-30] Add LLMs.txt generation

---

.github/workflows/pull-request.yml
pyproject.toml
uv.lock

Makes tests considerably faster

ci: Parallelise test execution

---

docs/code_examples/modal/editor_add_bitmask.py
docs/editor_agents/modal.md
docs/notebooks/hugging_face_agent_example.ipynb
docs/notebooks/llm_as_a_judge.ipynb
docs/notebooks/mask_rcnn_on_videos.ipynb
docs/notebooks/multistage_video_summarisation.ipynb
docs/notebooks/prelabel_videos_with_bounding_boxes.ipynb
docs/notebooks/yolo_example.ipynb
pyproject.toml
uv.lock

fix: Just introduce opencv-python-headless as the default dependency

---

uv.lock

https://linear.app/encord/issue/EC-6066/minor-upgrade-for-tornado

Updating tornado

---

.github/workflows/aikido.yml
uv.lock

https://linear.app/encord/issue/EC-6079/major-upgrade-for-setuptools

Adding manual scan and updating setuptools

---

docs/editor_agents/fastapi.md
docs/editor_agents/gcp.md
docs/editor_agents/spec.md
encord_agents/aws/__init__.py
encord_agents/aws/wrappers.py
encord_agents/core/data_model.py
encord_agents/core/exceptions.py
encord_agents/fastapi/__init__.py
encord_agents/fastapi/cors.py
encord_agents/gcp/__init__.py
encord_agents/gcp/wrappers.py
tests/integration_tests/fastapi/test_dependencies.py
tests/test_default_payload.py
tests/test_fastapi.py

Docs somewhat covered. Would be nice to amend one of the examples to actually use it but can be done later.

feat: [MLT-31] Editor Agent Response type

---

uv.lock

Could add this to the action 🤷 
Or ideally the bump will get more powerful

fix: regenerate it

---

.github/workflows/publish.yml

Fixed workflow secrets passing to publish docs pipeline

Fixed workflow secrets passing to publish docs pipeline

---

encord_agents/core/data_model.py
pyproject.toml
tests/fixtures.py
tests/integration_tests/tasks/test_queue_runner.py
uv.lock

Do we wanna create a data group on the test user and have an integration test.
Data group created + included in test coverage
TODO:
Do we wanna always fetch the children for editor agents potentially. Save our users from a foot-gun there.

feat: [MLT-72] Add data groups support.

---

docs/task_agents/sequential_runner.md

Was checking this page. Generally things could probably be improved around here

fix: English poor
